=begin
#Acqualify API Documentation

#The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.

OpenAPI spec version: 1.0.0
Contact: info@creditsaint.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.18

=end

module SwaggerClient
  VERSION = '1.0.0'
end
